language: node_js
node_js:
  - 14.15.1

stage:
  - test

cache:
  npm: true

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

jobs:
  include:
    - stage: test
      name: 'Unit tests and integration tests with test coverage'
      script: npm run test:coverage

    - stage: test
      name: 'Code Linting'
      script: npm run lint

    - stage: audit
      name: 'Security audits'
      script: npm audit

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
